#!/bin/bash -e

TEST_COUNTER=0
FAIL_COUNTER=0

function ok {
    TEST_COUNTER=$(($TEST_COUNTER+1))
    echo ok $TEST_COUNTER - $1
}

function not_ok {
    TEST_COUNTER=$(($TEST_COUNTER+1))
    FAIL_COUNTER=$(($TEST_COUNTER+1))
    echo not ok $TEST_COUNTER - $1
}

function xslt_test {
    in=$1
    tmp=${in%.xml}; from=${tmp##*.}
    base=${in%.$from.xml}
    out=$base.out.xml
    for script in ${from}2*.xsl; do
        tmp=${script%.xsl}; format=${tmp##*2}
        expect=$base.$format.xml        
        if [ -f "$expect" ]; then			
            xsltproc "$script" "$in" > $out
			if diff -Bb $out $expect > /dev/null
            then
                ok "$in $out # $script"
            else
                not_ok "$expect $out # $script"
			fi
        fi
    done
}

if [ "$#" -eq 0 ]; then
    for file in test/*.xml; do
        xslt_test $file
    done
else
    for file in "$@"; do
        xslt_test $file
    done
fi

# done_testing
echo 1..$TEST_COUNTER

exit $FAIL_COUNTER
